### ISSUE TITLE
Site does not show any records in code section!

### ISSUE THREAD

**Issue by tamtamchik** [microphp/microphp.github.com#4]
Hi there,

Site does not show any records in code section. Can you fix this?

<img width="1147" alt="2016-01-27 22 27 45" src="https://cloud.githubusercontent.com/assets/265510/12625520/3d6ea850-c545-11e5-87b4-1a1c5db60955.png">

**Comment by TCattd** [comment]
I think the issue here is this: https://gimmebar.com/api/v0/public/assets/funkatron/micro-php.json
API error: http://prntscr.com/b88qdy

@funkatron ?

**Comment by mindplay-dk** [comment]
I guess it's dead :-(

**Comment by funkatron** [comment]
Gimmebar is basically dead. Site could be brought back if we moved that
JSON out of it and/or made new data for those assets.
